import IconStr from '../../../assets/img/icon/icon-str.png';
import IconInt from '../../../assets/img/icon/icon-int.png';
import IconAgi from '../../../assets/img/icon/icon-agi.png';
import hoodwink from '../../../assets/img/hoodwink.png';
import dawnbreaker from '../../../assets/img/dawnbreaker.png';

export const heroesAttributes = [
  //str
  { name: 'abaddon', attributes: IconStr },
  { name: 'alchemist', attributes: IconStr },
  { name: 'axe', attributes: IconStr },
  { name: 'beastmaster', attributes: IconStr },
  { name: 'bristleback', attributes: IconStr },
  { name: 'centaur warrunner', attributes: IconStr },
  { name: 'chaos knight', attributes: IconStr },
  { name: 'clockwerk', attributes: IconStr },
  { name: 'dawnbreaker', attributes: IconStr },
  { name: 'doom', attributes: IconStr },
  { name: 'dragon knight', attributes: IconStr },
  { name: 'earth spirit', attributes: IconStr },
  { name: 'earthshaker', attributes: IconStr },
  { name: 'elder titan', attributes: IconStr },
  { name: 'huskar', attributes: IconStr },
  { name: 'io', attributes: IconStr },
  { name: 'kunkka', attributes: IconStr },
  { name: 'brewmaster', attributes: IconStr },
  { name: 'legion commander', attributes: IconStr },
  { name: 'lifestealer', attributes: IconStr },
  { name: 'lycan', attributes: IconStr },
  { name: 'magnus', attributes: IconStr },
  { name: 'mars', attributes: IconStr },
  { name: 'night stalker', attributes: IconStr },
  { name: 'omniknight', attributes: IconStr },
  { name: 'phoenix', attributes: IconStr },
  { name: 'pudge', attributes: IconStr },
  { name: 'sand king', attributes: IconStr },
  { name: 'slardar', attributes: IconStr },
  { name: 'snapfire', attributes: IconStr },
  { name: 'spirit breaker', attributes: IconStr },
  { name: 'sven', attributes: IconStr },
  { name: 'tidehunter', attributes: IconStr },
  { name: 'timbersaw', attributes: IconStr },
  { name: 'tiny', attributes: IconStr },
  { name: 'treant protector', attributes: IconStr },
  { name: 'tusk', attributes: IconStr },
  { name: 'underlord', attributes: IconStr },
  { name: 'undying', attributes: IconStr },
  { name: 'wraith king', attributes: IconStr },
  //abi
  { name: 'Anti-Mage', attributes: IconAgi },
  { name: 'arc warden', attributes: IconAgi },
  { name: 'bloodseeker', attributes: IconAgi },
  { name: 'bounty hunter', attributes: IconAgi },
  { name: 'broodmother', attributes: IconAgi },
  { name: 'clinkz', attributes: IconAgi },
  { name: 'drow ranger', attributes: IconAgi },
  { name: 'ember spirit', attributes: IconAgi },
  { name: 'faceless void', attributes: IconAgi },
  { name: 'gyrocopter', attributes: IconAgi },
  { name: 'hoodwink', attributes: IconAgi },
  { name: 'juggernaut', attributes: IconAgi },
  { name: 'lone druid', attributes: IconAgi },
  { name: 'luna', attributes: IconAgi },
  { name: 'medusa', attributes: IconAgi },
  { name: 'meepo', attributes: IconAgi },
  { name: 'mirana', attributes: IconAgi },
  { name: 'monkey king', attributes: IconAgi },
  { name: 'morphling', attributes: IconAgi },
  { name: 'naga siren', attributes: IconAgi },
  { name: 'nyx assassin', attributes: IconAgi },
  { name: 'pangolier', attributes: IconAgi },
  { name: 'phantom assassin', attributes: IconAgi },
  { name: 'razor', attributes: IconAgi },
  { name: 'riki', attributes: IconAgi },
  { name: 'shadow fiend', attributes: IconAgi },
  { name: 'slark', attributes: IconAgi },
  { name: 'sniper', attributes: IconAgi },
  { name: 'spectre', attributes: IconAgi },
  { name: 'templar assassin', attributes: IconAgi },
  { name: 'terrorblade', attributes: IconAgi },
  { name: 'troll warlord', attributes: IconAgi },
  { name: 'ursa', attributes: IconAgi },
  { name: 'vengeful spirit', attributes: IconAgi },
  { name: 'venomancer', attributes: IconAgi },
  { name: 'viper', attributes: IconAgi },
  { name: 'weaver', attributes: IconAgi },
  //int
  { name: 'ancient apparition', attributes: IconInt },
  { name: 'bane', attributes: IconInt },
  { name: 'batrider', attributes: IconInt },
  { name: 'chen', attributes: IconInt },
  { name: 'crystal maiden', attributes: IconInt },
  { name: 'dark seer', attributes: IconInt },
  { name: 'dark willow', attributes: IconInt },
  { name: 'dazzle', attributes: IconInt },
  { name: 'death prophet', attributes: IconInt },
  { name: 'disruptor', attributes: IconInt },
  { name: 'enchantress', attributes: IconInt },
  { name: 'enigma', attributes: IconInt },
  { name: 'grimstroke', attributes: IconInt },
  { name: 'invoker', attributes: IconInt },
  { name: 'jakiro', attributes: IconInt },
  { name: 'keeper of the light', attributes: IconInt },
  { name: 'leshrac', attributes: IconInt },
  { name: 'lich', attributes: IconInt },
  { name: 'lina', attributes: IconInt },
  { name: 'lion', attributes: IconInt },
  { name: 'natures prophet', attributes: IconInt },
  { name: 'necrophos', attributes: IconInt },
  { name: 'ogre magi', attributes: IconInt },
  { name: 'oracle', attributes: IconInt },
  { name: 'Outworld Devourer', attributes: IconInt },
  { name: 'puck', attributes: IconInt },
  { name: 'pugna', attributes: IconInt },
  { name: 'queen of pain', attributes: IconInt },
  { name: 'rubick', attributes: IconInt },
  { name: 'shadow demon', attributes: IconInt },
  { name: 'shadow shaman', attributes: IconInt },
  { name: 'silencer', attributes: IconInt },
  { name: 'skywrath mage', attributes: IconInt },
  { name: 'storm spirit', attributes: IconInt },
  { name: 'techies', attributes: IconInt },
  { name: 'tinker', attributes: IconInt },
  { name: 'visage', attributes: IconInt },
  { name: 'void spirit', attributes: IconInt },
  { name: 'warlock', attributes: IconInt },
  { name: 'windranger', attributes: IconInt },
  { name: 'winter wyvern', attributes: IconInt },
  { name: 'witch doctor', attributes: IconInt },
  { name: 'zeus', attributes: IconInt },
];

export const heroesNotImg = [
  { id: 121, img: dawnbreaker },
  { id: 120, img: hoodwink },
];
